### ISSUE TITLE
Initializing a new BitSet using a byte[]

### ISSUE THREAD

**Issue by kabua** [infusion/BitSet.js#12]
We have permission data stored as a byte[], can BitSet be initialized with a byte[]? If so, what would the syntax look like? something like: ```var bs = new BitSet(bitarray);```

And if not, how would we implement it?

**Comment by infusion** [comment]
What do you expect to be in the array? The indexes of bits to be set or just binary values? I ask because I'm about to finalize v4 and it got array arguments. The elements of the array contains the indexes of bits to be set to 1.

**Comment by kabua** [comment]
Sorry, I'm having a hard time trying to figure out what you mean by "The indexes of bits to be set or just binary values". I'm looking for the same functionality that [.NET BitArray(byte[] bytes)](https://msdn.microsoft.com/en-us/library/x1xda43a(v=vs.110).aspx) ctor provides.

Let me know if you have any other questions. Any chance we can get functionality by Thursday? Thanks!

**Comment by kabua** [comment]
To be precise, a BitSet that takes a Uint8Array.

We are, from the back end, encoding byte arrays (byte[]) into Base64 encoded strings. Then on the browser side we are decoding the Base64 string back into bytes (really Uint8Arrays) using [Base64-js](https://github.com/beatgammit/base64-js/blob/master/lib/b64.js). We could like to then use BitSet to manage the set of bits as a bit array.

**Comment by kabua** [comment]
After reviewing the code, here is "an" implementation that accepts creating BitSets from a Uint8Array.

Here is some test code:

    var fromTheWire = "JUI=";   // Byte array encoded in Base64.

    //        Byte:   1    0 
    //which equals: 0x42 0x25 or 100 0010 0010 0101, with (msb) ...to... (lsb) (Note: which, I believe, is in reverse order than Hex string inputs).
    var bytes = base64js.toByteArray(fromTheWire);

    var accessRighs = new BitSet(bytes);
    var ss = accessRighs.toString();    // expecting: "100 0010 0010 0101", actual: "100 0010 0010 0101"

    var test = 0;
    for(var i = 0; i < 16; i++)
    {
        test = rights.get(i);
        // for i = 0, 2, 5, 9, and 14 should equal true. All else should equal false.
    }


Code changes, I added the following to the end of parse(p)'s switch statement:

            case 'object':
                if (p instanceof Uint8Array) {
                    var bits = 8;

                    for (var i = 0; i < p.length; i++)
                    {
                        n = p[i];
                        for (var j = 0; j < bits; j++) {

                            var k = i * bits + j;
                            var slot = Math.floor(k / bitsPerInt);

                            if (!P[slot])
                                P[slot] = 0;

                            P[slot] |= (n >> j & 1) << (k % bitsPerInt);
                        }
                    }
                }
                else {
                    throw 'Invalid param';
                }
                break;

I assume the code could be cleaned up and changed to support more than just Uint8Arrays but this is all we need to keep moving forward. 

So, again, thank you for writing BitSet!

Note: base64js.toByteArray() came from [here](https://github.com/beatgammit/base64-js).

**Comment by infusion** [comment]
I'll push a new version tomorrow in the evening, I have a tight schedule atm, but I oriented on your question, if I can come up with a solution till tomorrow. Thanks for the code snippet, that helps in understanding what you're aiming for :)

**Comment by infusion** [comment]
Thanks for your patience and your participation in BitSet.js. I just published to the master. It's a really rough rewrite and please note, that I decided to make the library mutable.

If something breaks for you, please open a new ticket and I'll fix it! Otherwise, please let me know and I'll add the the tag v4.0.0 and publish it on npm.
