### ISSUE TITLE
It Appears that a Simple Test is Failing...

### ISSUE THREAD

**Issue by kabua** [infusion/BitSet.js#13]
We are trying to understand your library, so we wrote a very simple test and didn't get the results we were expecting. Are we doing something wrong?

***The Test:***

    var bs1 = new BitSet("101");
    var ss = bs1.toString(); // expecting "101", actual "101" Note: bs1 = {length=1, [0]=5}
    var a = bs1.get(1);      // expecting 0, actual 0
    var b = bs1.get(2);      // expecting 1, actual 1

    var bs2 = new BitSet("111");
    ss = bs2.toString();    // expecting "111", actual "111" Note: bs2 = {length=1, [0]=7}

    var bs3 = bs2.clear(1);
    ss = bs3.toString();     // expecting "101", actual "1" Note: bs3 = {length=2, [0]=1,[1]=0}
    var c = bs3.get(1);      // expecting 0, actual 0
    var d = bs3.get(2);      // expecting 1, actual 0
    var t = bs3.equals(bs1); // expecting true, actual false

Why is bs3's length equal to 2? If we understand things correctly, we believe length should be 1 and [0] should be 5.

**Comment by kabua** [comment]
I notice that the documentation states the following:

    /**
     * Clear a range of bits by setting it to 0
     *
     * Ex:
     * bs1 = new BitSet();
     * bs1.clear(); // Clear entire set
     * bs1.clear(5); // Clear single bit
     * bs1.clar(3,10); // Clear a bit range
     *
     * @param {number=} from The start index of the range to be cleared
     * @param {number=} to The end index of the range to be cleared
     * @returns {BitSet} this
     */

But the code, for the ```bs1.clear(5); // Clear single bit``` wasn't working. However, if we change

            if (to === undefined) {

                to = bitsPerInt * this['length'];
            }

to this...

        if (to === undefined) {

            to = from;
        }

It works just fine.

Hope this helps.

**Comment by infusion** [comment]
The test is now passing. The implementation is now somewhat different.
