### ISSUE TITLE
Usabiliity...

### ISSUE THREAD

**Issue by kabua** [infusion/BitSet.js#16]
For the most part, I like `BitSet` however, (taking a clue from "Prototype the User Experience"), I think the usability could be increased if you made the following changes:
1) All mathematical operations are immutable operations, which return back a new `BitSet` object.
2) All other function, those that changes the object, are mutable. (E.g. `Set()`, `SetRange()`, `Clear()`, and (perhaps) `Flip()`).

The reason for this is simple, I want to change the actual `BitSet` when I'm performing an operation directly on the object. However, like Math, operations like: '`and`', '`or`', "`not`' etc don't change the lhs or the rhs operands; they just return a new result value. Likewise, `BitSet` should do the same.

I just spent 20 minutes tracking down a very subtle but because I forget to assign the return value from a `Set` operation to itself. 

This code feel very natural: `permissions.set(Read)`
This doesn't feel natural: `permissions = permission.set(Read)`

Hope that helps.

**Comment by infusion** [comment]
This mutable thing will haunt me for a lifetime on this project, I think. I totally agree with you. To put it in a historical context: This project started with 1.0 in a mutable fashion. I then made all my JS libs immutable. Now #10 showed up and I also wanted to have the fastest bitset implementation (which I now achieved with 4.0) and said: okay, it's definitely not a project like complex.js where immutability is a must have and clone() if it's really necessary doesn't hurt. 

But I agree with you that some methods should have a mutable touch and some should better work in-place. However, I'm not a friend of mixing it up. What do you think about adding a new set of functions, prefixed by something like "new_", which calls the original function after an explicit clone()?

**Comment by kabua** [comment]
The problem with request #10 is what does he mean by 'especially for large bitsets'? Let's assume 250 bits to be large, if that is the case then 250 bits divided by 8 bits is only 32 bytes (rounded up) of data - that's only 8 ```Int32``` values - most modern CPUs can move 8 ```Int32``` values around without breaking a sweet. So, why have a strange (and perhaps) a confusing "User Experience" for a limited edge case? (Granted anything over 250 would be pushing it though but I suspect most bit sets to be under 32 bits.)

If the edge case is required, then what about making the new functions called something like ```and_inline``` and ```or_inline``` etc? That would perform the operations on itself (i.e."inline").

Example:
```
var resultset = bitset.and(otherSet);

bitset2.and_inline(otherSet2);
```

The readability and the meaning (I hope) is clear to any one review this code for the first time.

I don't like the, 'clone then op', that would be hiding potentially expensive operations that the developer could easily perform themselves.

I still like my original comments about having the bit setters work against itself but the Math operations return a new ```BitSet```. Just like [Set theory] (https://en.wikipedia.org/wiki/Set_theory) teaches us, the original sets are never modified during a set operation and what you have created is a 'set' of bits. Thus ```BitSet``` by definition, must function as a mathematical set - that is if you want this class to be widely adopted, that is.

Based upon this same reasoning, we discarded Microsoft's built-in C# ```BitArray``` class and we created our own ```BitVector``` class that follows these rules and our developers find it very intuitive and more natural than the ```BitArray``` class.

Hope this helps.

**Comment by mwpowellhtx** [comment]
I am interested in a bitset that is comparable to C# BitArray or C++ bitset or boost::bitset. I agree with the OP that set operations should be immutable. Doesn't matter how fast it is if the answer cannot be reasoned about, isn't correct.

**Comment by rvnath** [comment]
Hi, I am the one who raised issue#10.  My use case was to store a huge array of bits (of users).  The number of bits is typically of the order of millions (something like 1..10 millions).  To construct such a huge bitset, in the immutable case, I  observed that the performance goes down exponentially. For a few thousand numbers it works reasonably fast.  As the number reaches beyond 50K and above, the slowness starts (because each successive bit setting involves the copy of the original buffer, which by now has become big.

I use the large data, in order to create a bitset and store it a cache structure such as Redis.

**Comment by mwpowellhtx** [comment]
@rvnath I am using bitsets to represent statistical categories. So far seems like a good fit in my general as well as specific use cases. For instance, if I want to record "field goal attempt", then I have bits for "field", "goal", and "attempt". So the work for me is to build a vocabulary of these bits. So far so good, and my use case has grown to between 256-512 bits. I don't know what you do for more than that, however. I've implemented one such bitset and treat it as an array of 32-bit integers; don't know if that would be better/worse than this one, but immutability, idempotency, etc, are critical issues IMO. HTH

**Comment by infusion** [comment]
Okay, to finally come by this issue, what do you think about this change:

Keep Mutable
- set
- setRange
- clear
- flip


Make Immutable
- slice
- not
- and
- or
- xor
- andNot
- clone

Is Neutral
- get
- toArray
- cardinality
- msb
- ntz
- lsb
- isEmpty

**Comment by infusion** [comment]
Okay, version 5.0.0 just landed. The mutable/immutable behavior is like stated here and documented in the readme.md. Furthermore, a bug in the `and` function was found by fuzzing and is now fixed. Have fun with bitset.js further on! :)
