### ISSUE TITLE
Why is isEmpty false even when all bits are set to 0?

### ISSUE THREAD

**Issue by CMCDragonkai** [infusion/BitSet.js#22]
```js
a = new bs(new Uint8Array(32 / 8 - 1)).flip()
for (i = 0; i < 32; ++i) {
  a.set(i, 0);
}
a.isEmpty() // false?
```

**Comment by CMCDragonkai** [comment]
It seems like it will work if I set the range on the flip: `flip(0, 31)`.

I think I'm accustomed to fixed sizes bitsets and not arbitrary sized ones, I'm not understanding the usage  of the '_' property. It appears to change the behaviour of some functions.

**Comment by infusion** [comment]
The '_' property is simply an internal flag to store the MSB state on inversion. If for example `.set(10, 1).not().get(10000)` is executed, you would expect the result to be 1, since all the bits on higher indexed were turned to 1 from 0.

**Comment by infusion** [comment]
That means for your actual problem: The initial invocation of `.flip()` inverts '_' (using `.not()`) (BTW: I added a small note on the source file for the meaning of this flag). You then set the range from 0-31 to zero, using `.set()`, which doesn't alter the flag though. The same is true for flip, using an interval as parameter (`flip(0, 31)`). This does not change the infinity flag obviously, as only the small range has to be changed.
