### ISSUE TITLE
Webpack compatible version

### ISSUE THREAD

**Issue by jamesjryan** [infusion/BitSet.js#25]
Hi,

This is a great lib, especially the infinite length feature.

Is it possible to get a published version that is compatible with webpack using ES5 exports?

Many thanks!

**Comment by infusion** [comment]
Hi James,
locally I work on a new export pattern, which allows all my node modules to work with webpack, typescript, AMD/UMD, ... I need to finish this work and bring it to the modules. If you know a quick fix to keep you running, let me know.

**Comment by jamesjryan** [comment]
Robert,

Thanks so much for the prompt reply, that's great to hear.

I'm working on something today that requires bitset, and it works locally with imports but the build fails.

If you could publish a working copy that works with webpack on a separate branch, or even just a gist so I could include it as vendor code outside of node_modules that'd be fantastic.

**Comment by infusion** [comment]
From the code site, what changes are required? Export the module in ES6 style?

**Comment by jamesjryan** [comment]
Exporting as ES5 style, npm modules as ES6 still tends to cause issues with build systems.

**Comment by infusion** [comment]
bitset.js is getting exported with ES5. What is your actual error?

**Comment by jamesjryan** [comment]
`tsconfig.json`:

```
{
  "compilerOptions": {
    "baseUrl": "src",
    "outDir": "build/dist",
    "module": "es6",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "allowSyntheticDefaultImports": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/*.test.tsx",
    "src/setupTests.ts"
  ],
  "types": [
    "typePatches"
  ]
}
```
error:

```
 npm run build

> xxxxx@0.1.0 build /Users/xxxxx/Data/code/xxxxxx/client
> react-scripts-ts build

Creating an optimized production build...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
ts-loader: Using typescript@2.7.1 and /Users/xxxxx/Data/code/xxxxx/client/tsconfig.json
No valid rules have been specified
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/bitset/bitset.js:50

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxxxx@0.1.0 build: `react-scripts-ts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kepler@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by infusion** [comment]
Could you please try to configure bitset.js to be ignored by the minimizer of webpack?
