### ISSUE TITLE
Misleading comments on [im]mutable functions

### ISSUE THREAD

**Issue by vrachels** [infusion/BitSet.js#28]
In bitset.js, and the .d.ts in #27,  the comments for the bitwise operators include "The result is stored in-place".

I see that the Readme.md does show the correct immutable description, but the inline documentation should either be kept up to date, too, or remove it.

affected functions: and, or, andNot, not, xor

**Comment by vrachels** [comment]
also, toArray() suggests it could return Array | number

**Comment by infusion** [comment]
Thanks, that were good findings!
