### ISSUE TITLE
A `size()` method

### ISSUE THREAD

**Issue by PEZ** [infusion/BitSet.js#33]
Thanks for this library! In my testing, it is almost as fast as the one shipped with Java.

I need a way to know how big the bitset is. `size()` or `count()` or something like that.

This might be because the `forEach()` is still lacking, but I am not sure

**Comment by infusion** [comment]
Hi PEZ,

thanks! Nice to hear you like it and are happy with the performance :-) What do you mean by size of the bitset? 

- If you need the size of the allocated bitset, you can use `bs.data.length * 32`
- If you need the number of set bits, it is `bs.cardinality()`
- If you need the "width" as size of the bitset, you can calculate the most significant bit with `bs.msb()`

Where bs is your bitset `bs = new Bitset`. 

Or are you missing another size measure?

Robert

**Comment by infusion** [comment]
A new version landed where a BitSet object is iterable, if that helps.

**Comment by PEZ** [comment]
Hello. Sorry for the radio silence. It would be the `bs.data.length * 32` that I needed. But I will try the the iterable interface first. Thanks!
