### ISSUE TITLE
fromHex() and toHex() util methods

### ISSUE THREAD

**Issue by manikantag** [infusion/BitSet.js#4]
Hi, it would be nice to have `fromHex()` and `toHex()` methods as once we've the BitSet instance, sometimes we may want to persist that into Hex and decode that hex into BitSet later.

**Comment by infusion** [comment]
Hi,

I'm working on a bigger update, which will include something like that. I'm in the last stage: writing tests and fixing bugs. Give me two more days.

Robert

**Comment by infusion** [comment]
Okay, I was a little faster than expected. You can check out v2.0.0 which is able to parse strings as function argument and can `toString` the binary representation in a certain radix. For example:

```javascript
var x = new BitSet('0xdeadc0d3');
x.set('010101010101010101'); // Works for every function param now
console.log(x.toString(16)); // Print hex string
```
Robert
