### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by alexharri** [infusion/BitSet.js#49]
Hey, the README mentions that this library has been benchmarked against other libraries:

> [this library] is also heavily benchmarked against other implementations and is the most performant implementation to date.

The benchmarks don't seem to be included in the repository. Is there some way to find the source code for the benchmarks, and the results from them?

**Comment by infusion** [comment]
The benchmarks were hosted on jsperf, but they unfortunately took down the service and I therefore deleted the link to it.
