### ISSUE TITLE
Length of the bitset

### ISSUE THREAD

**Issue by mwpowellhtx** [infusion/BitSet.js#9]
Hello,

How "long" so to speak can the bitset be? I am considering a leap into JavaScript, React, Node, etc, and along with that, will need some sort of extensible bitset. Should be able to support arbitrary length bitsets, complete with bitwise operations, serialization to/from string, bit as well as hex or even base-n representation. Serialization might be pushing it, but it does need to be extensible. Wondering if this is that?

Might be similar along [these](https://github.com/tdegrunt/bitset/issues/12) lines. I see, for instance, that there are to/fromHex methods.

Thank you...

**Comment by infusion** [comment]
A BitSet is dynamically growing as "out of range" indexes are getting accessed/needed. The only missing piece for your use case is a fromHex method. toHex can be done with toString by giving the base as an argument.
